### ISSUE TITLE
Request to cdn.contentful.com failed, reason: socket hang up

### ISSUE THREAD

**Issue by ignatospadov** [contentful/contentful.js#2009]
This is a really weird issue. It happens intermittently with one of our applications. We have one application that does not use contentful's sdk library and makes direct GET requests to cdn.contentful.com. We never run into issues related to ECONNABORTED or socket hang up. The other application we get random alerts with ECONNABORTED and socket hang up and it uses the library SDK.

There is very little info on why this happens in the logs and on the internet. Both applications are using next.js, deployment is the same. The one with lower traffic is the one that has these connection issues all the time.

## Expected Behavior

Connection is not aborted

## Actual Behavior

Connection is aborted due to socket hang up

## Possible Solution

Not sure

## Steps to Reproduce

Not sure

## Context

```
Connection error occurred. Waiting for 2095 ms before retrying...
{"code":"ECONNABORTED","config":{"attempts":6,"baseURL":"[https://cdn.contentful.com:443/spaces/redacted/environments/master](https://cdn.contentful.com/spaces/redacted/environments/master)","headers":{"Accept":"application/json, text/plain, */*","Authorization":"Bearer redacted","Content-Type":"application/vnd.contentful.delivery.v1+json","User-Agent":"axios/0.26.1","X-Contentful-User-Agent":"sdk contentful.js/10.2.0; platform node.js/v18.12.0; os Linux/v18.12.0;"},"httpAgent":false,"httpsAgent":false,"maxBodyLength":1073741824,"maxContentLength":1073741824,"method":"get","params":{"content_type":"navigation"},"proxy":false,"retryOnError":true,"timeout":30000,"transformRequest":[null],"transformResponse":[null],"transitional":{"clarifyTimeoutError":false,"forcedJSONParsing":true,"silentJSONParsing":true},"url":"[https://cdn.contentful.com:443/spaces/redacted/environments/master/entries](https://cdn.contentful.com/spaces/redacted/environments/master/entries)","xsrfCookieName":"XSRF-TOKEN","xsrfHeaderName":"X-XSRF-TOKEN"},"message":"Error in _app.page.js  timeout of 30000ms exceeded","stack":"Error: timeout of 30000ms exceeded\n    at e.exports (/opt/app/node_modules/contentful/dist/contentful.node.min.js:1:11071)\n    at g.<anonymous> (/opt/app/node_modules/contentful/dist/contentful.node.min.js:1:4587)\n    at g.emit (node:events:513:28)\n    at g.emit (node:domain:552:15)\n    at Timeout.<anonymous> (/opt/app/node_modules/contentful/dist/contentful.node.min.js:1:32931)\n    at listOnTimeout (node:internal/timers:564:17)\n    at process.processTimers (node:internal/timers:507:7)","status":null}
[warning] Connection error occurred. Waiting for 3343 ms before retrying...
[warning] Connection error occurred. Waiting for 3480 ms before retrying...
[warning] Connection error occurred. Waiting for 1970 ms before retrying...
[warning] Connection error occurred. Waiting for 3459 ms before retrying...
[warning] Connection error occurred. Waiting for 4625 ms before retrying...
[warning] Connection error occurred. Waiting for 6162 ms before retrying...
[warning] Connection error occurred. Waiting for 6174 ms before retrying...
[warning] Connection error occurred. Waiting for 3416 ms before retrying...
[warning] Connection error occurred. Waiting for 2109 ms before retrying...
[warning] Connection error occurred. Waiting for 3435 ms before retrying...
[warning] Connection error occurred. Waiting for 2085 ms before retrying...
{"code":"ECONNABORTED","config":{"attempts":6,"baseURL":"[https://cdn.contentful.com:443/spaces/redacted/environments/master](https://cdn.contentful.com/spaces/redacted/environments/master)","headers":{"Accept":"application/json, text/plain, */*","Authorization":"Bearer redacted","Content-Type":"application/vnd.contentful.delivery.v1+json","User-Agent":"axios/0.26.1","X-Contentful-User-Agent":"sdk contentful.js/10.2.0; platform node.js/v18.12.0; os Linux/v18.12.0;"},"httpAgent":false,"httpsAgent":false,"maxBodyLength":1073741824,"maxContentLength":1073741824,"method":"get","params":{"content_type":"navigation"},"proxy":false,"retryOnError":true,"timeout":30000,"transformRequest":[null],"transformResponse":[null],"transitional":{"clarifyTimeoutError":false,"forcedJSONParsing":true,"silentJSONParsing":true},"url":"[https://cdn.contentful.com:443/spaces/redacted/environments/master/entries](https://cdn.contentful.com/spaces/redacted/environments/master/entries)","xsrfCookieName":"XSRF-TOKEN","xsrfHeaderName":"X-XSRF-TOKEN"},"message":"Error in _app.page.js  timeout of 30000ms exceeded","stack":"Error: timeout of 30000ms exceeded\n    at e.exports (/opt/app/node_modules/contentful/dist/contentful.node.min.js:1:11071)\n    at g.<anonymous> (/opt/app/node_modules/contentful/dist/contentful.node.min.js:1:4587)\n    at g.emit (node:events:513:28)\n    at g.emit (node:domain:552:15)\n    at Timeout.<anonymous> (/opt/app/node_modules/contentful/dist/contentful.node.min.js:1:32931)\n    at listOnTimeout (node:internal/timers:564:17)\n    at process.processTimers (node:internal/timers:507:7)","status":null}
{"code":"ECONNABORTED","config":{"attempts":6,"baseURL":"[https://cdn.contentful.com:443/spaces/redacted/environments/master](https://cdn.contentful.com/spaces/redacted/environments/master)","headers":{"Accept":"application/json, text/plain, */*","Authorization":"Bearer redacted","Content-Type":"application/vnd.contentful.delivery.v1+json","User-Agent":"axios/0.26.1","X-Contentful-User-Agent":"sdk contentful.js/10.2.0; platform node.js/v18.12.0; os Linux/v18.12.0;"},"httpAgent":false,"httpsAgent":false,"maxBodyLength":1073741824,"maxContentLength":1073741824,"method":"get","params":{"content_type":"navigation"},"proxy":false,"retryOnError":true,"timeout":30000,"transformRequest":[null],"transformResponse":[null],"transitional":{"clarifyTimeoutError":false,"forcedJSONParsing":true,"silentJSONParsing":true},"url":"[https://cdn.contentful.com:443/spaces/redacted/environments/master/entries](https://cdn.contentful.com/spaces/redacted/environments/master/entries)","xsrfCookieName":"XSRF-TOKEN","xsrfHeaderName":"X-XSRF-TOKEN"},"message":"Error in _app.page.js  timeout of 30000ms exceeded","stack":"Error: timeout of 30000ms exceeded\n    at e.exports (/opt/app/node_modules/contentful/dist/contentful.node.min.js:1:11071)\n    at g.<anonymous> (/opt/app/node_modules/contentful/dist/contentful.node.min.js:1:4587)\n    at g.emit (node:events:513:28)\n    at g.emit (node:domain:552:15)\n    at Timeout.<anonymous> (/opt/app/node_modules/contentful/dist/contentful.node.min.js:1:32931)\n    at listOnTimeout (node:internal/timers:564:17)\n    at process.processTimers (node:internal/timers:507:7)","status":null}
[warning] Connection error occurred. Waiting for 6176 ms before retrying...
[warning] Connection error occurred. Waiting for 6328 ms before retrying...
[warning] Connection error occurred. Waiting for 2062 ms before retrying...
[warning] Connection error occurred. Waiting for 2600 ms before retrying...
[warning] Connection error occurred. Waiting for 2023 ms before retrying...
```

**Comment by ignatospadov** [comment]
Closing this issue because the problem was related to network management in our infrastructure

**Comment by vineeth-bhat** [comment]
Hi @ignatospadov, we are facing similar issue with our setup. Which is similar to your setup with nextjs and contentful. We are using rather old version `8.5.0`. Even out system suddenly faces socket hang up issue and  the request to contentful API rather shows quite big latency. 

Do you mind telling us bit more what was the network management issue you faced in your infrastructure please ?
We were also leaning towards it but cannot figure it out, would be a great help to understand the issue. 

Thank you.
