### ISSUE TITLE
Error on IE11: ReferenceError: 'Promise' is undefined

### ISSUE THREAD

**Issue by mbryk** [contentful/contentful.js#207]
IE does not support the native [Promise](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Promise#Browser_compatibility)

Logged in console:
`ReferenceError: 'Promise' is undefined`
`  at n.prototype.request (https://unpkg.com/contentful@5.0.1/dist/contentful.browser.min.js:1:16110)`
`  at n.prototype[e] (https://unpkg.com/contentful@5.0.1/dist/contentful.browser.min.js:1:16432)`
`  at Anonymous function (https://unpkg.com/contentful@5.0.1/dist/contentful.browser.min.js:1:6695)`
`  at getEntries (https://unpkg.com/contentful@5.0.1/dist/contentful.browser.min.js:1:39925)`

Perhaps allow promises to be configurable, as requested in #94.

**Comment by mbryk** [comment]
Never mind. https://github.com/contentful/contentful.js#legacy-browsers
