### ISSUE TITLE
Maximum call stack size errors when using httpAgent

### ISSUE THREAD

**Issue by TomiTakussaari** [contentful/contentful.js#272]
## Expected Behavior

Contentful.js is fast and does not error when fetching data from Contentful.

## Actual Behavior

We have node.js app, that loads data from Contentful. We were wondering why its quite slow, and while investigating, found out that contentful.js by default does not seem to use http keep-alive when connecting to CDA, meaning that new connection was opened for every time we asked for something, which was very, very slow, atleast for us.

So, we fixed this by giving HttpAgent & HttpsAgents, with keepAlive=true, to Contentful.js.

But now we get this kind of errors seemingly randomly:

```json

{ "error": {}, "level": "error", "message": "uncaughtException: Maximum call stack size exceeded\nRangeError: Maximum call stack size exceeded\n    at merge (/app/node_modules/contentful/dist/contentful.node.js:1928:15)\n    at assignValue (/app/node_modules/contentful/dist/contentful.node.js:1932:21)\n    at forEach (/app/node_modules/contentful/dist/contentful.node.js:1905:12)\n    at merge (/app/node_modules/contentful/dist/contentful.node.js:1939:5)\n    at assignValue (/app/node_modules/contentful/dist/contentful.node.js:1932:21)\n    at forEach (/app/node_modules/contentful/dist/contentful.node.js:1905:12)\n    at merge (/app/node_modules/contentful/dist/contentful.node.js:1939:5)\n    at assignValue (/app/node_modules/contentful/dist/contentful.node.js:1932:21)\n    at forEach (/app/node_modules/contentful/dist/contentful.node.js:1905:12)\n    at merge (/app/node_modules/contentful/dist/contentful.node.js:1939:5)", "stack": "RangeError: Maximum call stack size exceeded\n    at merge (/app/node_modules/contentful/dist/contentful.node.js:1928:15)\n    at assignValue (/app/node_modules/contentful/dist/contentful.node.js:1932:21)\n    at forEach (/app/node_modules/contentful/dist/contentful.node.js:1905:12)\n    at merge (/app/node_modules/contentful/dist/contentful.node.js:1939:5)\n    at assignValue (/app/node_modules/contentful/dist/contentful.node.js:1932:21)\n    at forEach (/app/node_modules/contentful/dist/contentful.node.js:1905:12)\n    at merge (/app/node_modules/contentful/dist/contentful.node.js:1939:5)\n    at assignValue (/app/node_modules/contentful/dist/contentful.node.js:1932:21)\n    at forEach (/app/node_modules/contentful/dist/contentful.node.js:1905:12)\n    at merge (/app/node_modules/contentful/dist/contentful.node.js:1939:5)", "exception": true, "date": "Fri Aug 31 2018 04:27:56 GMT+0000 (Coordinated Universal Time)", "process": { "pid": 31, "uid": 0, "gid": 0, "cwd": "/app", "execPath": "/usr/local/bin/node", "version": "v10.5.0", "argv": [ "/usr/local/bin/node", "/app/out/index.js" ], "memoryUsage": { "rss": 178384896, "heapTotal": 169328640, "heapUsed": 99921208, "external": 362567 } }, "os": { "loadavg": [ 0.13525390625, 0.04736328125, 0.03173828125 ], "uptime": 53884 }, "trace": [ { "column": 15, "file": "/app/node_modules/contentful/dist/contentful.node.js", "function": "merge", "line": 1928, "method": null, "native": false }, { "column": 21, "file": "/app/node_modules/contentful/dist/contentful.node.js", "function": "assignValue", "line": 1932, "method": null, "native": false }, { "column": 12, "file": "/app/node_modules/contentful/dist/contentful.node.js", "function": "forEach", "line": 1905, "method": null, "native": false }, { "column": 5, "file": "/app/node_modules/contentful/dist/contentful.node.js", "function": "merge", "line": 1939, "method": null, "native": false }, { "column": 21, "file": "/app/node_modules/contentful/dist/contentful.node.js", "function": "assignValue", "line": 1932, "method": null, "native": false }, { "column": 12, "file": "/app/node_modules/contentful/dist/contentful.node.js", "function": "forEach", "line": 1905, "method": null, "native": false }, { "column": 5, "file": "/app/node_modules/contentful/dist/contentful.node.js", "function": "merge", "line": 1939, "method": null, "native": false }, { "column": 21, "file": "/app/node_modules/contentful/dist/contentful.node.js", "function": "assignValue", "line": 1932, "method": null, "native": false }, { "column": 12, "file": "/app/node_modules/contentful/dist/contentful.node.js", "function": "forEach", "line": 1905, "method": null, "native": false }, { "column": 5, "file": "/app/node_modules/contentful/dist/contentful.node.js", "function": "merge", "line": 1939, "method": null, "native": false } ] }

```

Looking at lines, it seems to come from Axios bundled into contentful.js.

## Possible Solution

Axios had issue about this, https://github.com/axios/axios/issues/370 and apparently it is fixed in master, but not yet released. 
So upgrading axios dependency could help ?

## Environment

- Linux / OSX
- Nodejs 10.5
- Contentful.js 7.0.3

**Comment by axe312ger** [comment]
I just released `7.1.0-beta0` which contains the latest community Axios beta. Install via `npm i contentful@next`

Can you please give feedback if it solves your issue and works fine with your project?

Thanks a lot,
Benedikt

**Comment by TomiTakussaari** [comment]
Hi @axe312ger!

Our initial tests do indicate that this solves our issue. 
Thanks!

**Comment by TomiTakussaari** [comment]
No problems so far, so lets close this.

Thanks!
