### ISSUE TITLE
_ is not defined

### ISSUE THREAD

**Issue by kellyrmilligan** [contentful/contentful.js#37]
i'm getting this locally on a dev build of a site, I see the contentful.js module was just newly released

ReferenceError: _ is not defined
    at isParseableResource (/Users/kellymilligan/Documents/code/tm-web/node_modules/contentful/index.es5.js:391:10)
    at walkMutate (/Users/kellymilligan/Documents/code/tm-web/node_modules/contentful/index.es5.js:419:7)
    at parseSearchResult (/Users/kellymilligan/Documents/code/tm-web/node_modules/contentful/index.es5.js:400:3)
    at run (/Users/kellymilligan/Documents/code/tm-web/node_modules/babel-core/node_modules/core-js/modules/es6.promise.js:89:39)
    at /Users/kellymilligan/Documents/code/tm-web/node_modules/babel-core/node_modules/core-js/modules/es6.promise.js:100:28
    at flush (/Users/kellymilligan/Documents/code/tm-web/node_modules/babel-core/node_modules/core-js/modules/$.microtask.js:9:13)
    at process._tickDomainCallback (node.js:381:11)

**Comment by sdepold** [comment]
Hello @kellyrmilligan,

thanks for getting in touch with us. It's a pity that we didn't notice that problem earlier. Unfortunately the test helper that sits in front of the client during the tests is making lodash globally available which made the tests pass although lodash was never required in the lib itself. Therefore the tests were green but the lib itself would not be able to access it.

The referenced pull request will fix the issue :)

**Comment by cnrudd** [comment]
How do I make a new contentful.min.js that includes the lodash?  What is the command used in the command line to build a new dist folder using this fix?

-Colin

**Comment by sdepold** [comment]
Hi @cnrudd,

if you run both of the following commands, then you should be good to go:

```
npm run prepublish
npm run bower-build
```

**Comment by cnrudd** [comment]
Thank you.
That worked for making a minified version

This is what I ran to get an un-minified version:
browserify -s contentful --debug -t [ babelify --sourceMapRelative . ] index.es6.js > dist/contentful.expanded.js

-Colin
